DEFAULT_LAYERS = 5
DEFAULT_NODES = 20
DEFAULT_NUM_TRAIN = 32
DEFAULT_NUM_TEST = 100

ITERATIONS = 10000
ACTIVATION = 'tanh'
INITIALIZER = 'Glorot uniform'
OPTIMIZER = 'L-BFGS'
METRICS = ['l2 relative error']